### ISSUE TITLE
Change the name

### ISSUE THREAD

**Issue by bendrucker** [jamestalmage/angular-test-utils#3]
This is great work. Really, really, really great. It deserves to be recognized. And it's going to be harder to do that with a name like (angular|ng)-test-utils. No ideas are coming to mind right now, but my experience is that making a clever pun really doesn't matter. Being pronounceable and memorable is more important than describing the functionality.

**Comment by jamestalmage** [comment]
Agreed. I am just not sure what it should be. My other idea was just "ngtu" for short, but that is equally lame. I am not good at [naming things](http://martinfowler.com/bliki/TwoHardThings.html).

**Comment by jamestalmage** [comment]
Now published as TANG. (test annotations for angular)

I particularly like the new plugin names "gulp-tang", and "tangify", and "karma-tang".

**Comment by jamestalmage** [comment]
Now all we need is some clever taglines:

"Want leaner Angular tests? Just add Tang!"

"Thirsty for a better way to test Angular? Gulp some Tang!"

...something to do with astronauts...

**Comment by bendrucker** [comment]
Love it :smile:

**Comment by jamestalmage** [comment]
I missed a bunch of stuff on my first pass renaming and failed to wipe out my local node_modules folder before running the tests locally, so none of it was caught until it hit travis. Wait until I publish tang `0.1.1` before updating.

**Comment by jamestalmage** [comment]
OK,
I've got everything passing locally, and I think any remaining travis failures are related the service degradation they are currently reporting (builds are taking 5-6 times longer and failing randomly). I went ahead and publish 0.1.1. (some plugins are at 0.1.2)
